---
title: "linear_regression_models"
author: 'Zachary Katz (UNI: zak2132)'
date: "11/16/2021"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(viridis)

set.seed(1)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r}
data('nyc_airbnb')

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)

nyc_airbnb
```

Let's start with some visualizations

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) + 
  geom_point()
```

Let's fit a linear model...

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at this

```{r}
fit

summary(fit)

summary(fit)$coef

# Recommend using this broomy::tidy function
# Turns it into a data table
fit %>% broom::tidy()

```

If you want to present output...

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Borough: ")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```

We can take a quick look at diagnostics.

```{r}
# Use modelr package
# Residuals look pretty skewed to be honest
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = resid)) + 
  geom_density() + 
  xlim(-200, 200)
```

Let's try a different model..interactions? Nesting?

```{r}
# Check out interactions
fit = lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)
broom::tidy(fit)
```

Let's try nesting.

```{r}
# Nest smaller version of data sets within each borough
nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    # Use .x to assign temporary variable
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(borough, lm_results) %>% 
  unnest(lm_results) %>% 
  # Let's say you want to check stars only across boroughs
  filter(term == "stars")
```

Trying another example, e.g. looking at neighborhoods in Manhattan

```{r}
manhattan_lm_df = nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(-borough) %>% 
  relocate(neighbourhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(neighbourhood, lm_results) %>% 
  unnest(lm_results)

# In general, increasing the stars doesn't seem to make much of a difference in price
manhattan_lm_df %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) + 
  geom_density()

# Keeping star rating fit, how much does price change if I go from entire home to private room, or entire home to shared room, in each neighborhood?
manhattan_lm_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) + 
  geom_point() + 
  facet_grid(~term) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

